# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aistat < Formula
  desc "List active Claude Code and Codex sessions with real-time statuses"
  homepage "https://github.com/vburojevic/aistat"
  version "0.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/aistat/releases/download/v0.1.2/aistat_0.1.2_darwin_amd64.tar.gz"
    sha256 "b4db8744e6bbbe267d8ca42f7d2663894886fc0d8c517b3d7f0b3b26f839144d"

    def install
      bin.install "aistat"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/aistat/releases/download/v0.1.2/aistat_0.1.2_darwin_arm64.tar.gz"
    sha256 "6c45b17fdd8473f0f97e70cfe5701db05d644f9f86f44f9b28b2046e85f71853"

    def install
      bin.install "aistat"
    end
  end
end
