# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FantasticalCli < Formula
  desc "CLI for Fantastical URL handler and AppleScript"
  homepage "https://github.com/vburojevic/fantastical-cli"
  version "0.1.11"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.11/fantastical_0.1.11_darwin_amd64.tar.gz"
    sha256 "5c86c901749d79ad7a361654775c6b03c6ccabf07ea4eddb5de2334018ae1bd2"

    def install
      bin.install "fantastical"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.11/fantastical_0.1.11_darwin_arm64.tar.gz"
    sha256 "e9e53886f2d70be51b23b0aba7fc4c331f2a5d201618ec33025769557ae407e1"

    def install
      bin.install "fantastical"
    end
  end

  test do
    system "#{bin}/fantastical", "--version"
  end
end
