# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FantasticalCli < Formula
  desc "CLI for Fantastical URL handler and AppleScript"
  homepage "https://github.com/vburojevic/fantastical-cli"
  version "0.1.7"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.7/fantastical_0.1.7_darwin_amd64.tar.gz"
    sha256 "f8bc2e5b9148ebcf46637873c03310e29a06df5946985f91bfec2d29f59205e0"

    def install
      bin.install "fantastical"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.7/fantastical_0.1.7_darwin_arm64.tar.gz"
    sha256 "cd872d94017306022c5e766ed36c2a3e2b1989777e63bb35c08f52976760692f"

    def install
      bin.install "fantastical"
    end
  end

  test do
    system "#{bin}/fantastical", "--version"
  end
end
