# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcbolt < Formula
  desc "Modern Xcode CLI + TUI"
  homepage "https://github.com/vburojevic/xcbolt"
  version "0.1.47"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.47/xcbolt_0.1.47_darwin_amd64.tar.gz"
    sha256 "e772535b850f2c6e4bea824ed498ebbbc2310c84ae26f305f185730b5ae56562"

    def install
      bin.install "xcbolt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.47/xcbolt_0.1.47_darwin_arm64.tar.gz"
    sha256 "529be398511f2e2759fa4b11106b4c0cf0401aad27d0da79a1172473a1880f70"

    def install
      bin.install "xcbolt"
    end
  end

  test do
    system "#{bin}/xcbolt", "--help"
  end
end
