# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcbolt < Formula
  desc "Modern Xcode CLI + TUI"
  homepage "https://github.com/vburojevic/xcbolt"
  version "0.1.49"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.49/xcbolt_0.1.49_darwin_amd64.tar.gz"
    sha256 "3e2902f0f2712a2072b2ea7a8ccc8ea9df724f36e9141cf193dd649232eb3de7"

    def install
      bin.install "xcbolt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.49/xcbolt_0.1.49_darwin_arm64.tar.gz"
    sha256 "3bee2a888fec644cb27b93e3c2c50e61721a3dbdb8777fe3615b1d52bed054cd"

    def install
      bin.install "xcbolt"
    end
  end

  test do
    system "#{bin}/xcbolt", "--help"
  end
end
