# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcw < Formula
  desc "Tail iOS Simulator logs for AI agents"
  homepage "https://github.com/vburojevic/xcw"
  version "0.5.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/xcw/releases/download/v0.5.2/xcw_0.5.2_darwin_amd64.tar.gz"
    sha256 "e4a5d1586b384254d6aca4d5a24bfcd67ae592cb0cde74ba98f7b5e2812ab92b"

    def install
      bin.install "xcw"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/xcw/releases/download/v0.5.2/xcw_0.5.2_darwin_arm64.tar.gz"
    sha256 "3bf8ce949c17d9d9ec1a01115935ac2cc430f0e9894c12bdacad97ba8479f41b"

    def install
      bin.install "xcw"
    end
  end

  test do
    system "#{bin}/xcw", "version"
  end
end
